# Generated by Django 3.1.7 on 2021-11-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_comment',
            old_name='review',
            new_name='article',
        ),
    ]
