# Generated by Django 3.1.7 on 2021-11-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_path',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
