# Generated by Django 3.1.7 on 2021-11-19 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20211118_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
